DROP TABLE IF EXISTS SHOPPING_LIST;
DROP TABLE IF EXISTS COCKTAIL;
DROP TABLE IF EXISTS COCKTAIL_SHOPPING_LIST;

CREATE TABLE SHOPPING_LIST (
  ID UUID PRIMARY KEY,
  NAME TEXT
);

CREATE TABLE COCKTAIL (
  ID UUID PRIMARY KEY,
  NAME TEXT,
  GLASS TEXT,
  INSTRUCTIONS TEXT,
  IMAGE TEXT,
  STRINGEDREDIENT1 TEXT,
  STRINGEDREDIENT2 TEXT,
  STRINGEDREDIENT3 TEXT,
  STRINGEDREDIENT4 TEXT,
  STRINGEDREDIENT5 TEXT,
  STRINGEDREDIENT6 TEXT,
  STRINGEDREDIENT7 TEXT,
  STRINGEDREDIENT8 TEXT,
  STRINGEDREDIENT9 TEXT,
  STRINGEDREDIENT10 TEXT,
  STRINGEDREDIENT11 TEXT,
  STRINGEDREDIENT12 TEXT,
  STRINGEDREDIENT13 TEXT,
  STRINGEDREDIENT14 TEXT,
  STRINGEDREDIENT15 TEXT
);

CREATE TABLE COCKTAIL_SHOPPING_LIST (
  COCKTAIL_ID UUID REFERENCES COCKTAIL (ID) /*ON UPDATE CASCADE ON DELETE CASCADE*/,
  SHOPPING_LIST_ID UUID REFERENCES SHOPPING_LIST (ID) /*ON UPDATE CASCADE ON DELETE CASCADE*/,
  CONSTRAINT COCKTAIL_SHOPPING_LIST_PKEY PRIMARY KEY (COCKTAIL_ID, SHOPPING_LIST_ID)  -- explicit primary key
);